# Generated by Django 4.2.7 on 2025-08-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('suv', 'SUV'), ('van', 'Van'), ('bus', 'Bus'), ('luxury', 'Luxury Vehicle')], max_length=20)),
                ('package_type', models.CharField(choices=[('1day', '1 Day Trip'), ('3days', '3 Days Trip'), ('5days', '5 Days Trip'), ('custom', 'Custom Trip')], default='custom', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField(default=4)),
                ('is_available', models.BooleanField(default=True)),
                ('package_details', models.TextField(blank=True, help_text='Details about the travel package')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
